### ISSUE TITLE
Install instructions need `grunt build`

### ISSUE THREAD

**Issue by mpiasta-ca** [marcoslin/angularAMD-sample#2]
Without `grunt build` there are files missing when viewing with `grunt devel`. Need to run the build command first (or need to add the `build` task to run with `grunt setup`).

```
npm install
grunt setup
grunt build
grunt devel
```

**Comment by arloduff** [comment]
I'm actually getting an error on `grunt setup`:

    $ grunt setup
    Running "bower:setup" (bower) task
    Fatal error: Arguments to path.join must be strings

**Comment by dud3** [comment]
I'm getting the same error as well.
